version: 2
updates:
- package-ecosystem: 'pip'
  directory: "/backend"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 5
  groups:
    dependencies:
      patterns:
        - "*"

- package-ecosystem: "npm"
  directory: "/frontend"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 5
  groups:
    dependencies:
      patterns:
        - "*"

- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: monthly
    time: "09:00"
    timezone: "Asia/Tokyo"
